"""Shared helpers for the DR scripts.

Kept deliberately narrow so unit tests can target pure functions without
spinning up pg_dump or real S3. The CLI wrappers (`snapshot_db.py`,
`restore_db.py`, ...) orchestrate subprocess + boto3 calls on top of this.

Design notes
------------
- **Encryption**: AES-256-GCM with a 32-byte key supplied via the
  ``LOFTLY_DR_ENCRYPTION_KEY`` env var (hex-encoded). The 12-byte IV is
  generated with ``os.urandom`` per snapshot and **prepended** to the
  ciphertext. The 16-byte GCM tag is appended by ``cryptography``'s
  ``encryptor.finalize``; on the wire we emit ``iv || ciphertext || tag``
  so decryption is a mirror parse.
- **Object Lock**: we upload with ``ObjectLockMode='COMPLIANCE'`` and a
  30-day retention, which matches the bucket policy the founder creates in
  `docs/RUNBOOKS.md` (not in this repo). Object Lock is *per-version*, so
  re-uploading the same key is still safe.
- **Bucket layout**: ``s3://<bucket>/<env>/<YYYY-MM-DD>/postgres-<HH-MM-SS>.dump.enc``
  plus a sibling ``.manifest.json``. Env is baked into the prefix so a
  misconfigured staging run can never overwrite prod.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

if TYPE_CHECKING:
    from mypy_boto3_s3.client import S3Client
else:  # pragma: no cover - runtime import fallback; boto3 client is dynamic
    S3Client = Any


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Size of the random IV we prepend to every ciphertext. 12 bytes is the
#: canonical GCM nonce length.
IV_BYTES = 12

#: AES-256 key length in bytes.
KEY_BYTES = 32

#: Default bucket. Overridable via env for staging drills against a scratch
#: bucket. Kept module-level so tests can monkeypatch.
DEFAULT_BUCKET = os.environ.get("LOFTLY_DR_BUCKET", "loftly-dr-snapshots")

#: Object Lock retention window, in days. Matches runbook.
OBJECT_LOCK_DAYS = 30


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class DRError(Exception):
    """Base class for any DR-script error that should exit non-zero."""


class DRConfigError(DRError):
    """Missing / malformed env var or CLI arg."""


class DRDecryptError(DRError):
    """Ciphertext failed GCM auth tag (tamper or wrong key)."""


# ---------------------------------------------------------------------------
# Key loading
# ---------------------------------------------------------------------------


def load_encryption_key() -> bytes:
    """Read ``LOFTLY_DR_ENCRYPTION_KEY`` and return raw 32 bytes.

    Raises ``DRConfigError`` on missing / wrong-length / non-hex input.
    Generated by the founder with ``python -c "import secrets; print(secrets.token_hex(32))"``.
    """
    raw = os.environ.get("LOFTLY_DR_ENCRYPTION_KEY")
    if not raw:
        raise DRConfigError(
            "LOFTLY_DR_ENCRYPTION_KEY is unset. "
            "Generate with: python -c 'import secrets; print(secrets.token_hex(32))'"
        )
    try:
        key = bytes.fromhex(raw.strip())
    except ValueError as exc:
        raise DRConfigError("LOFTLY_DR_ENCRYPTION_KEY must be hex-encoded.") from exc
    if len(key) != KEY_BYTES:
        raise DRConfigError(
            f"LOFTLY_DR_ENCRYPTION_KEY must decode to {KEY_BYTES} bytes (got {len(key)})."
        )
    return key


# ---------------------------------------------------------------------------
# Encryption
# ---------------------------------------------------------------------------


def encrypt_bytes(plaintext: bytes, key: bytes) -> bytes:
    """AES-256-GCM encrypt. Returns ``iv || ciphertext || tag``.

    ``cryptography.AESGCM.encrypt`` already appends the 16-byte tag to the
    ciphertext, so we just prepend our fresh 12-byte IV and hand the whole
    blob back.
    """
    if len(key) != KEY_BYTES:
        raise DRConfigError(f"key must be {KEY_BYTES} bytes, got {len(key)}")
    iv = os.urandom(IV_BYTES)
    ct_and_tag = AESGCM(key).encrypt(iv, plaintext, associated_data=None)
    return iv + ct_and_tag


def decrypt_bytes(blob: bytes, key: bytes) -> bytes:
    """Reverse of ``encrypt_bytes``. Raises ``DRDecryptError`` on tamper."""
    if len(key) != KEY_BYTES:
        raise DRConfigError(f"key must be {KEY_BYTES} bytes, got {len(key)}")
    if len(blob) < IV_BYTES + 16:
        raise DRDecryptError("ciphertext too short to contain IV + GCM tag")
    iv = blob[:IV_BYTES]
    ct_and_tag = blob[IV_BYTES:]
    try:
        return AESGCM(key).decrypt(iv, ct_and_tag, associated_data=None)
    except Exception as exc:  # InvalidTag, etc.
        raise DRDecryptError(f"decryption failed — tamper or wrong key: {exc}") from exc


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SnapshotManifest:
    """Sidecar written next to every ciphertext.

    Pure-data — no behavior. Lets restore_db.py verify integrity (sha256)
    and row-count drift without connecting back to the source cluster.
    """

    env: str
    object_key: str
    sha256: str  # hex digest of the *ciphertext*
    size_bytes: int  # size of the ciphertext as uploaded
    created_at: str  # ISO8601 UTC
    row_counts: dict[str, int]
    pg_dump_format: str = "custom"
    schema_version: int = 1

    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2, sort_keys=True)

    @classmethod
    def from_json(cls, raw: str | bytes) -> SnapshotManifest:
        data = json.loads(raw)
        # Filter to declared fields so a newer manifest with extra keys is
        # still loadable on an older restore_db build.
        allowed = {f for f in cls.__dataclass_fields__}
        return cls(**{k: v for k, v in data.items() if k in allowed})


def build_manifest(
    *,
    env: str,
    object_key: str,
    ciphertext: bytes,
    row_counts: dict[str, int],
    now: datetime | None = None,
) -> SnapshotManifest:
    """Assemble a manifest from the ciphertext we're about to upload."""
    timestamp = (now or datetime.now(UTC)).replace(microsecond=0).isoformat()
    return SnapshotManifest(
        env=env,
        object_key=object_key,
        sha256=hashlib.sha256(ciphertext).hexdigest(),
        size_bytes=len(ciphertext),
        created_at=timestamp,
        row_counts=dict(row_counts),
    )


# ---------------------------------------------------------------------------
# R2 / S3 client
# ---------------------------------------------------------------------------


def build_r2_client(
    *,
    account_id: str | None = None,
    endpoint_url: str | None = None,
) -> S3Client:
    """Return a boto3 S3 client pointed at Cloudflare R2.

    Either ``account_id`` (preferred) or a fully-formed ``endpoint_url`` may
    be supplied. R2 signing uses region ``auto``; boto3 still insists on a
    region, so we pin it.
    """
    import boto3

    if endpoint_url is None:
        account = account_id or os.environ.get("CF_ACCOUNT_ID")
        if not account:
            raise DRConfigError("CF_ACCOUNT_ID is unset and no explicit endpoint_url provided.")
        endpoint_url = f"https://{account}.r2.cloudflarestorage.com"

    return boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        region_name="auto",
        aws_access_key_id=os.environ.get("R2_ACCESS_KEY_ID"),
        aws_secret_access_key=os.environ.get("R2_SECRET_ACCESS_KEY"),
    )


# ---------------------------------------------------------------------------
# Key naming
# ---------------------------------------------------------------------------


def build_object_key(env: str, now: datetime | None = None) -> str:
    """Produce ``<env>/<YYYY-MM-DD>/postgres-<HH-MM-SS>.dump.enc``."""
    t = (now or datetime.now(UTC)).replace(microsecond=0)
    return f"{env}/{t.strftime('%Y-%m-%d')}/postgres-{t.strftime('%H-%M-%S')}.dump.enc"


def manifest_key_for(object_key: str) -> str:
    """Sidecar path: replace ``.dump.enc`` suffix with ``.manifest.json``."""
    if not object_key.endswith(".dump.enc"):
        raise DRConfigError(f"unexpected object key suffix: {object_key!r}")
    return object_key[: -len(".dump.enc")] + ".manifest.json"


def parse_snapshot_uri(ref: str, *, bucket: str = DEFAULT_BUCKET, env: str) -> tuple[str, str]:
    """Turn a user-supplied ``ref`` into a ``(bucket, object_key)`` pair.

    Accepts either:

    - full ``s3://bucket/key/with/slashes.dump.enc``
    - a date shorthand ``YYYY-MM-DD`` — the caller is expected to resolve it
      to an exact object via ``list_objects_v2`` (see ``list_snapshots``).
      We just return the date-prefixed folder here.
    """
    if ref.startswith("s3://"):
        without = ref[len("s3://") :]
        parts = without.split("/", 1)
        if len(parts) != 2:
            raise DRConfigError(f"malformed s3 URI: {ref!r}")
        return parts[0], parts[1]
    # Date shorthand — caller will list & pick.
    if len(ref) == 10 and ref[4] == "-" and ref[7] == "-":
        return bucket, f"{env}/{ref}/"
    raise DRConfigError(f"snapshot ref {ref!r} must be an s3:// URI or a YYYY-MM-DD date.")
